### ISSUE TITLE
中文近义词工具包

### ISSUE THREAD

**Issue by Samurais** [Shuang0420/knowledge_graph_demo#1]
hi, 我也在研究知识图谱

我做了一个近义词库，可以辅助知识图谱的检索，而且每个词带有距离，可以用于相似度比较。
https://github.com/huyingxi/Synonyms

**Comment by wuqixiaobai** [comment]
您好，这个demo代码不知道是否共享呢？学习下

**Comment by Shuang0420** [comment]
好哒谢谢分享~
