### ISSUE TITLE
OError: [Errno 2] No such file or directory: 'medicine_114_basic.json'

### ISSUE THREAD

**Issue by Kaixinguoer210** [Shuang0420/knowledge_graph_demo#3]
你好，代码中没有medicine_114_basic.json文件，也没有任何关于这个文件的描述，这肿莫破？

**Comment by Shuang0420** [comment]
不好意思忘记改了，实际上就是 medicine_company_list.txt 这个包含股票代码的文件。已经上传了最新代码~谢谢提醒~
