### ISSUE TITLE
visualization

### ISSUE THREAD

**Issue by hopeldy** [Shuang0420/knowledge_graph_demo#4]
你好，
     请问demo中只能展示，600129这个公司的关系图么？如果我想展示其他公司的关系图怎么办，，希望能抽空解惑下，十分感谢！

**Comment by Juary88** [comment]
改下data.json

**Comment by Shuang0420** [comment]
可以显示别的，url 改 id 就好，比如说 http://localhost:8080/api/v1?company=600276
但是有个问题，上传的数据并不是完整数据，所以有些公司没法响应。可以运行爬虫爬取全部信息~
