### ISSUE TITLE
spo

### ISSUE THREAD

**Issue by zihsin** [Shuang0420/knowledge_graph_demo#5]
你好。
models.py中
edge_sql_comp = """SELECT subj, obj, pred, company.company_name, company.code, person.name, type 
FROM spo 
JOIN company 
JOIN person 
WHERE spo.subj=company.id AND **spo.obj=person.id** AND company.code=%s;""" 

spo这个表中的obj并不是person的id，这样连接是否有误？

博客中“management 保存了原始的关系，”董事”、监事”等，而 spo 把这些关系都映射成”高管”，也就是说 management 可能需要通过映射才能得到 SPO 表，SPO 才是最终成型的表”，但是spo表中的数据并不是公司和人员之间的高管关系，请问该怎么理解？

**Comment by Shuang0420** [comment]
spo表中的数据包括了公司和人员之间的高管关系（type="relation"，此时 obj 就是 person_id），但不仅限于此，表中还包括了公司的所有属性信息（type="property"）
所以运行的结果大概是下面这个样子的：
<img width="769" alt="sample" src="https://user-images.githubusercontent.com/14067092/34636067-7993a484-f2d4-11e7-9f99-ef28906dd3a5.png">

**Comment by zihsin** [comment]
好的，谢谢，是我对spo的数据没看仔细
